### ISSUE TITLE
Goto Offset doesn't accept Hex values

### ISSUE THREAD

**Issue by ShadowOne333** [bwrsandman/Bless#12]
I've been using Bless for quite a while now, and it has helped me a lot with debugging and reverse-engineering some binaries.

However, one drawback I found when using it is that the "Goto Offset" option (Ctrl-G) doesn't seem to accept any Hex values for its search, only decimal values.

I was wondering if this is a missing feature, or if I have to enable it somehow.
And if it's a missing feature, I'd like to recommend implementing a Goto Offset option which accepts Hexadecimal values as its parameter, as some of the files I edit through it tend to be quite big, and it takes a while to get to the desired offset at hand.

**Comment by melissalinkert** [comment]
Have you tried prefixing the hex value with ```0x```?  The manual notes that octal, hexadecimal, and decimal values are all supported in the ```Go to Offset``` bar, but octal and hexadecimal values require a specific prefix:

https://github.com/bwrsandman/Bless/blob/master/doc/user/bless-manual.xml#L737

**Comment by ShadowOne333** [comment]
You are correct.
By typing '0x' before the address I'm looking for, it does recognize the characters as an Hexadecimal offset.
Thanks for the heads up!
