### ISSUE TITLE
Feature: File templates

### ISSUE THREAD

**Issue by vdun** [bwrsandman/Bless#3]
Would be great to have the support of file templates/structure like :
- 010Editor: [http://www.sweetscape.com/010editor/repository/templates/]
  - Helpful tools:
    - [https://github.com/d0c-s4vage/pfp]
    - [https://github.com/d0c-s4vage/py010parser]
- Okteta: [https://docs.kde.org/trunk5/en/kdesdk/okteta/tools-structures.html]

This by making `Bless` able to read `.bt` or/and `.osd` files.

**Comment by Beercow** [comment]
This would be a very cool feature.

**Comment by bwrsandman** [comment]
This is a fork, please refer to https://github.com/afrantzis/bless
