### ISSUE TITLE
Single bytes of a byte offset are sometimes written in reverse

### ISSUE THREAD

**Issue by dbMansfield** [bwrsandman/Bless#6]
Here's an interesting bug in the offset display area.

Consider the offset as 4 bytes which are each a pair of characters. If a byte should contain exactly one `f` in its left character e.g. `f0` or `fa` then that byte is instead displayed in reverse e.g. `0f` or `af`. If the byte is `ff` then it is not displayed at all, and the byte is left blank.

![screenshot from 2017-09-12 23-18-41](https://user-images.githubusercontent.com/2227078/30351011-3ca25eb2-9811-11e7-87af-a07002fc85cb.png)

See the `d0`, `e0`, `0f` sequence in the picture for an example. I missed this originally but also see that the `f` is repeated; the display should be `0000ef50` and not `0000eff50`. I suspect this is all due to an error in [RenderRowNormal](https://github.com/bwrsandman/Bless/blob/f13da9facf23d46a477cb370b527b4dc75e9078b/src/gui/areas/OffsetArea.cs#L92), but I haven't been able to get the code to compile so I can't check. This is on Linux, if that's useful.

**Comment by max-weller** [comment]
Just wanted to note that I just experienced the same bug on Archlinux with MATE desktop.

**Comment by bwrsandman** [comment]
This is a fork, please refer to https://github.com/afrantzis/bless
