### ISSUE TITLE
Error saving file

### ISSUE THREAD

**Issue by jonnygrant** [bwrsandman/Bless#7]
Hello

I have 35GB free on this drive, so think this isn't accurate.
I'm using v0.6.0 on latest Ubuntu

==================
Error saving file '/home/jon/testfile.txt'

There is not enough free space on the device to safe file
'lvmtedq.bless'.
[OK]
===================

**Comment by jonnygrant** [comment]
lvmtedkq.bless

**Comment by trivia211** [comment]
Hey,

Open Edit/Preferences, and change Temporary Directory to /tmp. You should be able to save the file now.

Check if it still works after you relaunch Bless. My bet is that it doesn't. There is a bug in saving the preferences. See my posts #8 and #11 for a fix here:
[https://bugs.launchpad.net/ubuntu/+source/bless/+bug/1622951](https://bugs.launchpad.net/ubuntu/+source/bless/+bug/1622951)

**Comment by jonnygrant** [comment]
Sorry, I can't be re-compiling any software. Please supply an official 
updated package.

**Comment by trivia211** [comment]
I'm just a user of bless, like you. There seems to be no changes to the software since three years. I can send you the binaries I compiled for Ubuntu 16.04 x64 if you want.

**Comment by jonnygrant** [comment]
Hi, thank you for replying.

Ah ok, another unmaintained package...

I'd pay for software, if it got better quality..

**Comment by Tanimodori** [comment]
There's a workaround by fixing the temp dir, **the end of the preferences.xml** and making it read-only.
The fixed preferences.xml may look like
```
<preferences>
	<pref name="ByteBuffer.TempDir">/tmp</pref>
	...
	<pref name="Default.Layout.File"/>
</preferences>
```
Now it can save properly after relauching, this works on my Ubuntu 16.04 x64 computer.

**Comment by vido89** [comment]
Preferences xml file is stored at /usr/share/bless/default-preferences.xml

**Comment by joshi1983** [comment]
I ran into this problem too.  Bless is highly recommended but this is a pretty silly bug that makes me not want to recommend it to anyone.

**Comment by LightningStalker** [comment]
This fixes the problem but I had to save a file before the settings would take.

**Comment by bwrsandman** [comment]
This is a fork, please refer to https://github.com/afrantzis/bless
