### ISSUE TITLE
auto updating on file changes sometimes not triggered properly

### ISSUE THREAD

**Issue by woodz-** [bwrsandman/Bless#8]
Good evening,
I am generating and viewing binary files on a synology nas, mounted by cifs. Sometimes it hapens on overwriting a currently opened file in bless, it will not see the change and thus won't trigger the update.
My current workaround is to open the same file (another tab pops up by then) and magically the original file tab provides the reload / ignore feature.
Would love to see a manual refresh button or entry in "view" menue

Greetings woodz

**Comment by bwrsandman** [comment]
This is a fork, please refer to https://github.com/afrantzis/bless
